name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'mkdir -p /home/ubuntu/Uni-Pro-Backend'
        rsync -avz --exclude='.git*' ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/Uni-Pro-Backend/

    - name: Install dependencies and restart services
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        cd /home/ubuntu/Uni-Pro-Backend
        bundle install --without development test
        yarn install
        RAILS_ENV=production bundle exec rake db:migrate
        RAILS_ENV=production bundle exec rake assets:precompile
        sudo systemctl restart rails-app.service
        sudo systemctl restart node-signal-server.service
        EOF
